### ISSUE TITLE
OpenIddict refresh required on VS2017 code

### ISSUE THREAD

**Issue by bweeres** [PacktPublishing/ASPdotNET-Core-and-Angular-2#14]
The changes required to support a later version of OpenIddict were detailed in an issue that is now closed but the source code has not been updated. This is such an important part of the final chapters of this book that it seems that either the code should be updated or a new branch is created with the updates.

**Comment by kunal105** [comment]
can the code be updated for angular 4

**Comment by Darkseal** [comment]
Answering this after 1 year, sorry about that.

Perhaps you already know, but I wrote another book for Angular 5, and will stick to that pattern (1 book for each major version) since the changes are simply too many to keep updating the same book / code sample repo.

Here's the new book link:
https://www.packtpub.com/application-development/aspnet-core-2-and-angular-5
