### ISSUE TITLE
Does not build & run using latest version of .net

### ISSUE THREAD

**Issue by mdonogma** [PacktPublishing/ASPdotNET-Core-and-Angular-2#6]
downloaded code as-is
tried to build - indicated code was created with    "version": "1.0.0-preview2-003121" so I updated global to    "version": "1.0.0-preview2-003131"
does not run.

please can you update the GitHub code to run on latest vs.2015 update 3 with latest .net core SDK.

also many of the references in the .json files refer to old or beta packages (What is the best way to rectigy.)

also latest code indicates issues with openiddict when build (See chapter 9 code)

**Comment by AndrewCarre** [comment]
Start a new .net project and look in the global.json file to see the version that you have installed. Then copy it and put it in the project and it should compile. 

For whatever reason .net core is not backwards compatible. Hopefully they'll fix this in the 2.0 release.

**Comment by Darkseal** [comment]
Unfortunately, I cannot give much support for newer ASP.NET Core versions and/or newer package versions (including Angular4)  because they keep changing a lot. I'm working to a second edition that will address them all, but be aware of the fact that these are moving technologies so you will always have to update the references/syntax/interfaces by yourself as the time goes by... We can't avoid that.
