### ISSUE TITLE
Stuck on "Loading..."

### ISSUE THREAD

**Issue by AndrewCarre** [PacktPublishing/ASPdotNET-Core-and-Angular-2#7]
Hi I am having an issue where the browser is stuck loading. Looking at the dev console, it seems that a bunch of libraries are not being loaded. I did a 'npm install' and 'dotnet restore' (which I shouldn't have to do either and I am still having this issue. Has anyone else encountered this problem?
http://i.imgur.com/n0dElNK.png

**Comment by jpeng74** [comment]
Yes, i'm having the exact same problem. 
I'm on chapter 3 page 105 and followed step by step and I still get "Loading..." in index.html page.  It does not show the list items of the component.  I thought it may have been a caching issue but I double checked and it is now.  I need help also.

**Comment by jpeng74** [comment]
I finally figured out the issue:

in the systemjs.config.js, make sure you add 'forms'

 // configure @angular packages
    var ngPackageNames = [
      'common',
      'compiler',
      'core',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'upgrade',
      'forms'
    ];

**Comment by Darkseal** [comment]
Just to clarify, 'forms' is present in source code since the first commit. 

https://github.com/PacktPublishing/ASPdotNET-Core-and-Angular-2/blob/master/src/OpenGameListWebApp_Chapter07/wwwroot/systemjs.config.js

Be sure to check your source with GitHub source (possibly using text comparison software such as WinMerge) to avoid opening these kind of issues.
